# Generated by Django 5.2.16 on 2026-07-28 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Descripción"
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("hamburguesa", "Hamburguesa"),
                            ("pizza", "Pizza"),
                            ("completo", "Completo"),
                            ("acompanamiento", "Acompañamiento"),
                            ("bebida", "Bebida"),
                            ("postre", "Postre"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Precio",
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="Stock")),
                (
                    "disponible",
                    models.BooleanField(default=True, verbose_name="Disponible"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["nombre"],
            },
        ),
    ]
