# Generated by Django 5.2.16 on 2026-07-28 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="precio",
            field=models.DecimalField(
                decimal_places=0,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        500, message="El precio mínimo permitido es $500."
                    )
                ],
                verbose_name="Precio",
            ),
        ),
    ]
