# Generated by Django 5.2.16 on 2026-09-01 23:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_alter_producto_precio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        max_length=255, verbose_name="Dirección de entrega"
                    ),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[("Tarjeta", "Tarjeta"), ("Efectivo", "Efectivo")],
                        max_length=20,
                        verbose_name="Método de pago",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "costo_envio",
                    models.DecimalField(
                        decimal_places=0,
                        default=2990,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Costo de envío",
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Descuento",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Total",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("confirmado", "Pedido confirmado"),
                            ("preparacion", "En preparación"),
                            ("en_camino", "En camino"),
                            ("entregado", "Entregado"),
                        ],
                        default="confirmado",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha del pedido"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="DetallePedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Precio unitario",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_pedido",
                        to="menu.producto",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="menu.pedido",
                        verbose_name="Pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de pedido",
                "verbose_name_plural": "Detalles de pedido",
            },
        ),
    ]
